// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsJX1V4WQ2UC0wCn9Kx6Hu8SavqrbJJ0E',
    appId: '1:69042973969:web:74fafdd4176ac784c230b0',
    messagingSenderId: '69042973969',
    projectId: 'invice-app-dbd3d',
    authDomain: 'invice-app-dbd3d.firebaseapp.com',
    storageBucket: 'invice-app-dbd3d.appspot.com',
    measurementId: 'G-CEXY9HPGFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDM-ZMyxZINVcXxYEczNvHb3T5oTcNCw',
    appId: '1:69042973969:android:f1026e2b284d9144c230b0',
    messagingSenderId: '69042973969',
    projectId: 'invice-app-dbd3d',
    storageBucket: 'invice-app-dbd3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAobBBZBmNG0LxWOomBNZl-1ESv9jfWZ0Q',
    appId: '1:69042973969:ios:adc6701e92d86574c230b0',
    messagingSenderId: '69042973969',
    projectId: 'invice-app-dbd3d',
    storageBucket: 'invice-app-dbd3d.appspot.com',
    iosBundleId: 'com.example.flutterInvoiceApp',
  );
}
